name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v3
    - name: Build and run the Docker image
      run: | 
            cd /home/saradha/actions-runner/_work/self-hosted/self-hosted
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker build . --file Dockerfile --tag node:v3
            docker run -d --name node.app -p 82:82 node:v3
            
            
      
